server:
  port: 8030

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: test-001
